### PR TITLE
v2 Refactor

### PR DESCRIPTION
**Pull request by mitchellbutler**
As I mentioned in #5, I'm opening this as a new PR which doesn't include changes to the readme and package JSON. Since you're willing to roll these changes into the main repo, I don't need to host it on my own `npm` account.

---

Hey @smakosh , I can see this repo hasn't been touched in a while and I'd like to use Dribbble as a source on my personal Gatsby site. I've made some updates to the library for my own use and I'm wondering if you'll consider adopting them on the core project.

1. Most shot cover images are now stored locally so that they can benefit from [Gatsby's image pipeline](https://www.gatsbyjs.org/docs/working-with-images/) (`gatsby-plugin-sharp`, `gatsby-transformer-sharp`, `gatsby-image`). This should make sites that use the plugin much lighter and faster.
2. The graphql nodes are now renamed from ~`DribleUser`~ to **`DribbbleUser`** and from ~`AllDribleProjects`~ to **`AllDribbbleShot`** for clarity and consistency with most other `gatsby-source-...` packages. This also future-proofs the naming convention in case that support is added for Dribbble projects (which are different from shots).
3. I've added configs for linting and Prettier, and moved dependencies like babel into the `package.json` to make contributing easier.

Let me know what you think!

### CODE REVIEW

**Comment by mitchellbutler** [comment]
From the other thread:

> Would you like to update the starter's queries as well before merging this and updating the npm package: https://github.com/smakosh/gatsby-source-dribbble-example

Will do, looking into this now.

**Review by smakosh — APPROVED** [review]
LGTM, thanks for contributing!

**Comment by smakosh** [comment]
@all-contributors please add @davewasmer for refactoring and enhancements

**Comment by smakosh** [comment]
@all-contributors please add @davewasmer Code

**Comment by mitchellbutler** [comment]
I think you've got my username wrong, I'm @mitchellbutler :)

**Comment by smakosh** [comment]
@all-contributors please add @mitchellbutler for Code

**Comment by smakosh** [comment]
@mitchellbutler I updated the npm package: https://www.npmjs.com/package/gatsby-source-dribbble

**Comment by davewasmer** [comment]
I mean, I'll take credit if you'd like, but yea, don't think I've contributed to this repo 😆

**Comment by mitchellbutler** [comment]
Hey @smakosh, it looks like one of the built files is missing. Can you try running `build` in the repo and publishing again? Thanks!

**Comment by smakosh** [comment]
Updated 👌

**Pull request merged**
