### PR TITLE
Add .npmignore

### PR DESCRIPTION
**Pull request by mitchellbutler**
Sorry, this is why the build isn't working. I just noticed it mixed in with the Readme commits on my test repo. Can we merge this in and re-publish. It should be the last change we need before I can send you the PR on the examples repo!

### CODE REVIEW

**Comment by mitchellbutler** [comment]
Sorry again for the confusion @smakosh. Let me know once this has been added and the repo has been built & published. It should resolve the missing file issue.

I've also updated the example repo [here](https://github.com/smakosh/gatsby-source-dribbble-example/pull/2) but I'll have to wait until this is fixed to confirm that it works with this repo. Then I can retire my copy.

Also, you can check out the latest version in production on my [personal site](https://mitchellbutler.com/).

Cheers 🍻

**Review by smakosh — APPROVED** [review]
Thanks a lot @mitchellbutler and love your website!

**Comment by smakosh** [comment]
It has been published @mitchellbutler

**Comment by mitchellbutler** [comment]
Great! I've unpublished my `npm` version and archived the forks. 🎉

**Pull request merged**
